[build]
builder = "dockerfile"

[deploy]
startCommand = "sh -c 'label-studio start --host 0.0.0.0 --port ${PORT:-8080} --data-dir /app/data'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
LABEL_STUDIO_HOST = "0.0.0.0"
LABEL_STUDIO_PORT = "$PORT"
DJANGO_DB = "default"
DEBUG = "false"
LABEL_STUDIO_BASE_DATA_DIR = "/label-studio/data"
LABEL_STUDIO_MEDIA_ROOT = "/label-studio/media"

# Database configuration will be set via Railway environment variables
# POSTGRE_NAME, POSTGRE_USER, POSTGRE_PASSWORD, POSTGRE_HOST, POSTGRE_PORT

[environments.production.variables]
LABEL_STUDIO_HOST = "0.0.0.0"
LABEL_STUDIO_DATA_DIR = "/app/data"
LABEL_STUDIO_MEDIA_DIR = "/app/media"
DJANGO_SETTINGS_MODULE = "label_studio.settings.label_studio"
LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK = "true"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
POSTGRES_DB = "${{Postgres.POSTGRES_DB}}"
POSTGRES_USER = "${{Postgres.POSTGRES_USER}}"
POSTGRES_PASSWORD = "${{Postgres.POSTGRES_PASSWORD}}"
POSTGRES_HOST = "${{Postgres.POSTGRES_HOST}}"
POSTGRES_PORT = "${{Postgres.POSTGRES_PORT}}"

# Performance optimizations
WEB_CONCURRENCY = "2"
WORKER_CONNECTIONS = "1000"
MAX_WORKER_CONNECTIONS = "2000"

# Security settings
SECURE_SSL_REDIRECT = "true"
SESSION_COOKIE_SECURE = "true"
CSRF_COOKIE_SECURE = "true"

[environments.production.services]
postgres = { plan = "hobby" }