[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "label-studio start --host 0.0.0.0 --port $PORT --data-dir /label-studio/data"
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[environments.production]
LABEL_STUDIO_HOST = "0.0.0.0"
LABEL_STUDIO_PORT = "$PORT"
DJANGO_DB = "default"
DEBUG = "false"
LABEL_STUDIO_BASE_DATA_DIR = "/label-studio/data"
LABEL_STUDIO_MEDIA_ROOT = "/label-studio/media"

# Database configuration will be set via Railway environment variables
# POSTGRE_NAME, POSTGRE_USER, POSTGRE_PASSWORD, POSTGRE_HOST, POSTGRE_PORT

[environments.production.variables]
DJANGO_SETTINGS_MODULE = "label_studio.settings.label_studio"
LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK = "true"
LABEL_STUDIO_USERNAME = "admin"
LABEL_STUDIO_PASSWORD = "admin123"
LABEL_STUDIO_USER_TOKEN = ""

# Performance optimizations
WEB_CONCURRENCY = "2"
WORKER_CONNECTIONS = "1000"
MAX_WORKER_CONNECTIONS = "2000"

# Security settings
SECURE_SSL_REDIRECT = "true"
SESSION_COOKIE_SECURE = "true"
CSRF_COOKIE_SECURE = "true"